apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: kaft-main
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: kaft-main
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "f6fde9e6-3666-4ce2-a5c0-b4b20085c2ee"
      secretKeyName: internal-jwt-secret
