apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-lipl-stg-app
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/kigawa-net/platform.git
    targetRevision: main
    path: lipl/stg
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-lipl-stg

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
